name: Compilation test

on: [push, pull_request]

jobs:
  build:
    name: Build the contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://node:14.16.0
      - run: npm install
      - run: npm run build
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKENN: ${{ secrets.GITHUB_TOKEN }}
