name: Compilation test

on: [push, pull_request]

jobs:
  build:
    name: Build the contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ethereum/solc:0.7
      - run: npm install
      - run: npm run compile
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKENN: ${{ secrets.GITHUB_TOKEN }}
